-- Rescue scenario — UUID generated by Java UUID.randomUUID()
CREATE TABLE simulations (
    id          CHAR(36)     NOT NULL,
    name        VARCHAR(500) NOT NULL,
    description TEXT,
    created_by  VARCHAR(200),
    status      ENUM('active','ended') NOT NULL DEFAULT 'active',
    created_at  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ended_at    DATETIME(3),
    PRIMARY KEY (id),
    INDEX idx_simulations_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- List of cells forced OFF inside a simulation
CREATE TABLE simulation_overrides (
    simulation_id CHAR(36)    NOT NULL,
    cell_id       VARCHAR(50) NOT NULL,
    forced_status TINYINT(1)  NOT NULL DEFAULT 0,
    PRIMARY KEY (simulation_id, cell_id),
    INDEX idx_sim_overrides_sim (simulation_id),
    CONSTRAINT fk_so_simulation FOREIGN KEY (simulation_id)
        REFERENCES simulations(id) ON DELETE CASCADE,
    CONSTRAINT fk_so_cell FOREIGN KEY (cell_id)
        REFERENCES cells(cell_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
